### ISSUE TITLE
Can it be publish this in bower?

### ISSUE THREAD

**Issue by anandanand84** [FarhadG/code-mirror-themes#2]
It would be good if we publish this in bower and npm by adding bower.json and npm.json

**Comment by FarhadG** [comment]
Thanks for the recommendation, @anandanand84. I'll go ahead and add it to `bower` here shortly.

**Comment by FarhadG** [comment]
`bower` and `npm` support added, @anandanand84.

Closing issue 👍

**Comment by anandanand84** [comment]
Thats awesome! Thankyou
