### ISSUE TITLE
Multiline array alignment woes

### ISSUE THREAD

**Issue by gamecubate** [FarhadG/code-mirror-themes#3]
I am not sure why all themes get the alignment of array entries wrong:
```
var blocks = ["header",
              "main",
              "footer"];
```
Where things go wrong: items 2 and 3 ("main" and "footer") begin one space to the right of "header".

In my case, using ClojureScript, vector alignment fails the same way:
```
(def blocks
  [:header
   :main
   :footer])
```

The problem can be reproduced by going to the [themes test page](http://farhadg.github.io/code-mirror-themes/) and copy/pasting any of the above snippets.

## Monokai
![image](https://cloud.githubusercontent.com/assets/1483884/23309643/82a7c988-fa7d-11e6-88ae-5be3d70b16ba.png)

If you're busy I can help but some guidance may be needed (not sure where to begin looking).

**Comment by gamecubate** [comment]
Found it. Commenting out the ```word-spacing``` attribute fixes alignment issues (at risk of ruining something else though I have yet to spot that):
```
.cm-s-monokai {
	font-size: 1em;
	line-height: 1.5em;
	font-family: inconsolata, monospace;
	letter-spacing: 0.3px;
	/*word-spacing: 1px;*/
	background: #272822;
	color: #F8F8F2;
}
```

**Comment by FarhadG** [comment]
Nice find, @gamecubate! Thanks for reporting this and providing a solution. Feel free to submit a PR for this fix and I'll gladly merge it in.

**Comment by gamecubate** [comment]
I modified the .css file manually. I'd be happy to send in a PR were it not for the fact that the theme generator -- correct me if I'm wrong -- is a third-party's, which takes me beyond the time I have (schedule wise) to help fix this. Sorry. :(

**Comment by FarhadG** [comment]
It's all good, @gamecubate. Feel free to submit the PR for the manually updated `.css`.
