### ISSUE TITLE
VS Code Dark Plus Theme?

### ISSUE THREAD

**Issue by karlhorky** [FarhadG/code-mirror-themes#6]
Hi there, first of all, thanks so much for these themes! Great to see contributions like these to the CodeMirror community!

Would you be open to including a VS Code Dark Plus theme, based on the official default theme for VS Code?

https://github.com/microsoft/vscode/blob/main/extensions/theme-defaults/themes/dark_plus.json

I saw this over here, which may be fairly close, but I think needs a few tweaks to get right:

https://github.com/winitop/Theme-VSCode-Dark

**Comment by karlhorky** [comment]
Ah, I guess these themes here are outdated as of CodeMirror v6.

I've added a new VS Code Dark Plus theme for CodeMirror v6 here: https://github.com/upleveled/theme-vs-code-dark-plus

**Comment by FarhadG** [comment]
Would be great to open a PR and contribute to the project, if you'd like @karlhorky. I'm sure others will find it very useful

**Comment by karlhorky** [comment]
@FarhadG Do you know how to use the themes in this repo with the new Extension method of creating themes for CodeMirror v6?

eg. take a look at https://github.com/upleveled/theme-vs-code-dark-plus/blob/main/src/vs-code-dark-plus.ts - this is the new way of creating themes

**Comment by FarhadG** [comment]
It looks like a JS solution for CSS. I would need to look into the documentation but I'd imagine you can 1) use CSS as is and supplement it or 2) the ability to have the CSS file provided as a `string` to a function within this context. If not, then I'd need to update the repo to convert CSS to their JS implementation

**Comment by karlhorky** [comment]
Yeah, I am using [`@uiwjs/react-codemirror`](https://uiwjs.github.io/react-codemirror/), which doesn't seem to support the old CSS way of doing it, which is why I converted to the new extension way of doing things.

But feel free to take the code from above and add a CSS file in this repo from the colors! https://github.com/upleveled/theme-vs-code-dark-plus/blob/main/src/vs-code-dark-plus.ts#L119-L191
